### ISSUE TITLE
How could I get deepgo_tf?

### ISSUE THREAD

**Issue by maovshao** [Shen-Lab/TALE#1]
Hey guys, this is a very meaningful work and attracts me a lot. Thanks you for sharing your work!

But I met a problem when I tried to reproduce your work.  Which is
----No module named 'deepgo_tf'----

I tried "pip install deepgoplus". It works but cannot solve this problem.
Can you tell me how to get "deepgo_tf"? By the way, a more detailed dependence is needed.

Thans a lot again!

**Comment by Shen-Lab** [comment]
Thank you for the interest and the question!  @YueCao2017 Could you please help out?  Our model does not rely on DeepGo so it is unclear to me why importing deepgo_tf  was necessary, let alone the code is not working  https://github.com/Shen-Lab/TALE/blob/master/src/train.py#L19  Meanwhile you commented out Lines 17-18 but you do need HMCNF, which is also baffling.  Thanks.

**Comment by YueCao94** [comment]
Hi @maovshao !  Thank you for your question! Our codes indeed do not rely on deepgo_tf, which is a mistake in the previous version.  I have updated the codes and you can re-download. Thank you again!
