### ISSUE TITLE
Scaling in dot-product attention

### ISSUE THREAD

**Issue by ebrahimpichka** [Shen-Lab/TALE#5]
In the `attention_layer.py` file, where the attention mechanism is implemented, scaling the attention weights is done by `q *= depth**0.5` in line 126 (mentioned below).

Shouldn't it be done by division instead of multiplication i.e. `q /= depth**0.5` according to the [paper](https://arxiv.org/pdf/1706.03762.pdf)?

![image](https://user-images.githubusercontent.com/52668571/230253415-320d0ee2-1722-43ac-a812-2fea14f90e4b.png)
 

https://github.com/Shen-Lab/TALE/blob/b68b76973f730e69d3a0564e8ad1aec677015228/src/Protein_Encode/attention_layer.py#L126

```diff
+q /= depth**0.5
-q *= depth**0.5
```

**Comment by yang-shen** [comment]
Thank you for your interest in our work and attentions to the details.  Greatly appreciated!  Mathematically q *= depth ** -0.5 (notice the negative sign of the power) and q /= depth**0.5 are equivalent, right?

**Comment by ebrahimpichka** [comment]
Oh, I did miss the negative sign there, sorry. Thank you very much for the response.
